# Generated by Django 2.2.9 on 2020-07-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_locations_locations_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='survived',
            field=models.BooleanField(null=True),
        ),
    ]
