# Generated by Django 2.2.9 on 2020-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200705_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ticket_class',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
