# Generated by Django 2.0.4 on 2020-07-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_entry_ticket_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='survived',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='ticket_class',
        ),
    ]
