# Generated by Django 2.0.4 on 2020-07-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200705_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='Agent_Company',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Provider_Company',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
