# Generated by Django 2.0.4 on 2020-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200706_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='STS_latitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='STS_longitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
