# Generated by Django 2.0.4 on 2020-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200706_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='STS_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='STS_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
