# Generated by Django 2.2.9 on 2020-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200709_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='Provider_Company',
        ),
        migrations.AddField(
            model_name='entry',
            name='Provider_company',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
