# Generated by Django 2.2.9 on 2020-07-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20200714_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='list',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='flag1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='flag2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='flag3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
