# Generated by Django 2.2.9 on 2020-07-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20200715_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='trytologintime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='username',
            field=models.CharField(max_length=1000),
        ),
    ]
