# Generated by Django 2.2.9 on 2020-07-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200718_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='STS_Latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='STS_Longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='degrees_latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='degrees_longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
