# Generated by Django 2.2.9 on 2020-07-27 19:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20200720_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_details',
            name='Fees_to_be_incurred_for_STS_Operations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Cargos_permitted',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Oil', 'Oil'), ('LPG', 'LPG'), ('Chemicals', 'Chemicals'), ('LNG', 'LNG'), ('All cargoes permitted', 'All cargoes permitted')], max_length=1000, null=True),
        ),
    ]
